name: Commit Workflow

on:
  push:
    branches: [Feature-A]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: 
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
          
    - uses: actions/upload-artifact@v1
      with:
        name: verademo.war
        path: target/verademo.war


  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: pipeline scan
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: get archive
        uses: actions/download-artifact@v2
        with:
          name: verademo.war
      - name: pipeline-scan action step
        id: pipelien-scan
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.3
        #julz0815/Veracode-pipeline-scan-action@beta-0.29
        with:
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          file: "verademo.war"
          request_policy: "Verademo Policy"
          #request_policy: "VeraDemo Policy"
          #store_baseline_file: true
          #store_baseline_file_branch: "feature-A"
          #create_baseline_from: "standard"
          #debug: 1
          fail_build: false

  veracode-sca-task:
    runs-on: ubuntu-latest
    name: SCA scan

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v1.09
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: true

  import-policy-flaws:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    steps:
      - name: get flaw file
        uses: actions/download-artifact@v2
        with:
          name: policy-flaws
          path: /tmp

      - name: import flaws as issues
        uses: veracode/veracode-flaws-to-issues@v1
        with:
          scan-results-json: '/tmp/policy_flaws.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}